# creamos la BD:
CREATE DATABASE IF NOT EXISTS pizzeria2;
# relacionar la BD
USE pizzeria2;
#creamos las tablas

CREATE TABLE IF NOT EXISTS pedido(
id INT NOT NULL AUTO_INCREMENT,
Cliente CHAR (5) NOT NULL,
Fecha 	DATE NOT NULL,
Hora 	TIME NOT NULL,
Tienda 	CHAR (5) NOT NULL, 
PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS cliente(
id INT NOT NULL AUTO_INCREMENT,
NomCli VARCHAR (45) NOT NULL,
Apellido VARCHAR (30) NOT NULL,
Direccion VARCHAR (30) NOT NULL,
CodPostal VARCHAR (5) NOT NULL,
Telefono VARCHAR (9) NOT NULL,
NomLoca VARCHAR (40) NOT NULL,
PRIMARY KEY (id)
#id_localidad VARCHAR (40) NOT NULL,
#FOREIGN KEY(id_localidad) 
#REFERENCES localidad(id)
)

CREATE TABLE IF NOT EXISTS localidad(
id INT NOT NULL AUTO_INCREMENT,
NomLoca VARCHAR (40) NOT NULL,
PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS provincia(
id INT NOT NULL AUTO_INCREMENT,
NumProv CHAR (5) NOT NULL,
LocaProv VARCHAR (40) NOT NULL,
NomProv VARCHAR (40) NOT NULL,
PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS productos(
id INT NOT NULL AUTO_INCREMENT,
RefProd  INT (10) NOT NULL,
NomProd  VARCHAR (40) NOT NULL,
DesProd  VARCHAR (40) NOT NULL,
ImgProd	 VARCHAR (40) NOT NULL,
PreProd  DECIMAL (4,2) NOT NULL,
CatProd  INT (10), 
PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS categorias(
id INT NOT NULL AUTO_INCREMENT,
RefCat  INT (10) NOT NULL,
NomCat  VARCHAR (40) NOT NULL,
PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS articulospedido(
id INT NOT NULL AUTO_INCREMENT,
RefPddo  INT (10) NOT NULL,
ProPddo  INT (10) NOT NULL,
CantPddo CHAR (5) NOT NULL,
PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS tienda(
id INT NOT NULL AUTO_INCREMENT,
TieDir VARCHAR (30) NOT NULL,
TieCP  VARCHAR (5) NOT NULL,
TieLoc VARCHAR (40) NOT NULL,
PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS empleados(
id INT NOT NULL AUTO_INCREMENT,
EmpNom VARCHAR (40) NOT NULL,
EmpApe VARCHAR (40) NOT NULL,
EmpNif VARCHAR (9) NOT NULL,
EmpTfn VARCHAR (9) NOT NULL,
EmpTienda CHAR (2) NOT NULL, 
EmpCat CHAR (2) NOT NULL,
PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS catempleado(
id INT NOT NULL AUTO_INCREMENT,
Categoria VARCHAR (40) NOT NULL,
PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS entrega(
id INT NOT NULL AUTO_INCREMENT,
EntPedido CHAR (5) NOT NULL,
EntTienda CHAR (5) NOT NULL,
EntEmpleado CHAR (5) NOT NULL,
EntHora  TIME NOT NULL,
PRIMARY KEY (id)
)






